### PR TITLE
Memory leak from serial_controller #5

### PR DESCRIPTION
**Pull request by elhayra**
https://github.com/rbonghi/roboteq_control/issues/5

### CODE REVIEW

**Comment by rbonghi** [comment]
Thank you! I will merge soon!! :fireworks:

**Comment by rbonghi** [comment]
I have some questions for you :-)

In your pull request and I notice you comment or remove all parts about the dynamic reconfigure. This part is useful to setup the roboteq board, and when the node works doesn't leak the memory.

I also see you enable the motor controller without pass the parameters from urdf. I think in my package there is not a nice example to setup the URDF the board and run this package.

I'm making an example :+1:

**Comment by elhayra** [comment]
@rbonghi 
The truth is this was a long time ago, and I'm no longer work with Roboteq HW. But, I do remember that when I tried to use dynamic reconfigure it caused dynamic reconfigure GUI to crash, so I had to remove it in order to be able to use it along with other nodes.

About the second part - you are right. This is just customization I did for my purposes, and should not be included in your library.

Sorry for not filtering some of those things out, as I mentioned - this was a long time ago and I no longer have access to the HW for testing.

**Comment by rbonghi** [comment]
Hi @elhayra ,

I completely update my repository adding a example to show how it's work, and I hope now is more clear.

If there are more issues keep me posted.

I apologize for my delay

**Pull request closed without merging**
